networks:
    cncf-stacks:

services:
    prometheus:
        image: prom/prometheus
        ports:
            - 9000:9000
        networks:
            - cncf-stacks
    
    grafana:
        image: grafana/grafana
        user: "0"
        environment: 
            - GF_USERS_ALLOW_SIGN_UP=false
        ports:
            - 3000:3000
        volumes: 
            - grafana:/var/lib/grafana
        networks:
            - cncf-stacks
    
volumes: 
    grafana: